version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ML_models:/app/ML_models
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn web_app:main --host 0.0.0.0 --port 8000 --reload
